# Generated by Django 5.2 on 2025-07-13 13:19

import courses.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('overview', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('allowed_groups', models.ManyToManyField(blank=True, related_name='courses', to='auth.group')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectable', models.BooleanField(default=False, help_text='Se True, il gruppo appare nel dropdown di registrazione')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
                ('unlocked_groups', models.ManyToManyField(blank=True, related_name='unlocked_modules', to='auth.group')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', courses.fields.RichTextField()),
                ('order', models.IntegerField(default=0)),
                ('content_type', models.CharField(choices=[('text', 'Testo'), ('image', 'Immagine'), ('audio', 'Audio'), ('document', 'Documento'), ('link', 'Link'), ('assignment', 'Compito'), ('discussion', 'Discussione'), ('poll', 'Sondaggio'), ('video', 'Video'), ('quiz', 'Quiz')], max_length=50)),
                ('unlocked_groups', models.ManyToManyField(blank=True, related_name='unlocked_contents', to='auth.group')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='courses.module')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='file', max_length=200)),
                ('file', models.FileField(upload_to='resources/')),
                ('description', models.TextField(default='Nessuna descrizione')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.content')),
            ],
        ),
    ]
