# Generated by Django 5.2 on 2025-05-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.TextField(default='Nessuna descrizione'),
        ),
    ]
