# Generated by Django 5.2 on 2025-05-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('courses', '0002_resource_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
    ]
