# Generated by Django 5.2 on 2025-05-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('courses', '0003_course_allowed_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='allowed_groups',
            field=models.ManyToManyField(to='auth.group'),
        ),
    ]
