# Generated by Django 5.2 on 2025-05-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('courses', '0005_remove_course_allowed_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, related_name='courses', to='auth.group'),
        ),
        migrations.AddField(
            model_name='module',
            name='unlocked_groups',
            field=models.ManyToManyField(blank=True, related_name='unlocked_modules', to='auth.group'),
        ),
    ]
