# Generated by Django 5.2 on 2025-05-13 20:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('courses', '0007_resource_title_alter_course_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='unlocked_groups',
            field=models.ManyToManyField(blank=True, related_name='unlocked_contents', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='content',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
